; CapsLock-layer AHK v2 hotkeys. The complete default layout lives in
; The trusted shortcut seed is stored in cfg_defaults and overlaid by user rows.

global LayerKeyNames := Map(
    "a", "a", "b", "b", "c", "c", "d", "d", "e", "e", "f", "f", "g", "g", "h", "h", "i", "i", "j", "j", "k", "k", "l", "l", "m", "m", "n", "n", "o", "o", "p", "p", "q", "q", "r", "r", "s", "s", "t", "t", "u", "u", "v", "v", "w", "w", "x", "x", "y", "y", "z", "z",
    "1", "1", "2", "2", "3", "3", "4", "4", "5", "5", "6", "6", "7", "7", "8", "8", "9", "9", "0", "0",
    "F1", "f1", "F2", "f2", "F3", "f3", "F4", "f4", "F5", "f5", "F6", "f6", "F7", "f7", "F8", "f8", "F9", "f9", "F10", "f10", "F11", "f11", "F12", "f12",
    "Space", "space", "Tab", "tab", "Enter", "enter", "Esc", "esc", "Backspace", "backspace", "RAlt", "ralt",
    "-", "minus", "=", "equal", "[", "leftSquareBracket", "]", "rightSquareBracket", "\", "backslash", ";", "semicolon", "'", "quote", ",", "comma", ".", "dot", "/", "slash"
)
LayerKeyNames["SC029"] := "backquote"

global PasteSystemHotkeyRunning := false
global CapsLockTargetPath := ""
global CapsLockTargetHwnd := 0

BuildKeySet() {
    global KeySet
    KeySet := Map()
    for key, value in ConfigSection("Keys")
        if Trim(String(value)) != ""
            KeySet[key] := value
    DebugLog("KeySet press_caps=" . (KeySet.Has("press_caps") ? KeySet["press_caps"] : "<missing>"))
}

MakeActionHandler(actionKey) {
    return (*) => RunLayerAction(actionKey)
}

; Centralize the hook prefix so every CapsLock-layer hotkey is protected from
; synthetic output generated by SendInput inside a layer action.
RegisterCapsLayerHotkey(hotkeyName, callback) {
    Hotkey("$" . hotkeyName, callback)
}

RegisterCapsHotkeys() {
    ; Keep CapsLock as one blocking hotkey, like the reference implementation.
    ; Waiting for release here prevents the native CapsLock toggle and keeps the
    ; layer active for the complete key-hold interval.
    ; `$` is required for every blocking layer hotkey: layer actions use
    ; SendInput, and their output must never re-enter another layer hotkey.
    RegisterCapsLayerHotkey("CapsLock", CapsLockPress)
    RegisterCapsLayerHotkey("<!CapsLock", CapsLockWithAltPress)

    RegisterCapsLayerHotkeys()
}

; Register the complete layer once and use a condition to activate it only
; while the physical CapsLock key is held. This follows the reference
; project's #If CapsLock layout and leaves ordinary shortcuts, including
; Backspace and Alt+V, available at idle.
RegisterCapsLayerHotkeys() {
    global LayerKeyNames
    HotIf(CapsLockLayerActive)
    try {
        ; Keep the `$` prefix on every entry. For example, caps_w sends a
        ; Backspace which is itself a layer key; without `$` it becomes
        ; caps_backspace and changes the action into delete-line.
        for physicalKey, suffix in LayerKeyNames
            RegisterCapsLayerHotkey(physicalKey, MakeActionHandler("caps_" . suffix))
        RegisterCapsLayerHotkey("LAlt", (*) => 0)

        for physicalKey, suffix in LayerKeyNames
            RegisterCapsLayerHotkey("<!" . physicalKey, MakeActionHandler("caps_lalt_" . suffix))
        RegisterCapsLayerHotkey("<!WheelUp", MakeActionHandler("caps_lalt_wheelUp"))
        RegisterCapsLayerHotkey("<!WheelDown", MakeActionHandler("caps_lalt_wheelDown"))

        DebugLog("Caps layer static registration complete")
    } finally {
        HotIf()
    }
}

PasteSystemHotkey(*) {
    global PasteSystemHotkeyRunning
    if PasteSystemHotkeyRunning {
        DebugLog("Ctrl+V re-entry ignored")
        return
    }
    PasteSystemHotkeyRunning := true
    try {
        DebugLog("Ctrl+V hotkey received")
        if ClipboardEnabled()
            keyFunc_pasteSystem()
        else
            SendInput("^v")
    } finally {
        PasteSystemHotkeyRunning := false
    }
}

CapsLockLayerActive(*) {
    ; Do not depend on the CapsLock hotkey thread reaching its cleanup code.
    ; Long-running panel/clipboard actions can keep that thread alive after the
    ; physical key has already been released. The physical state is the only
    ; reliable boundary for deciding whether a normal key should be blocked.
    return GetKeyState("CapsLock", "P")
}

CapsLockPress(*) {
    HandleCapsLockPress(true)
}

CapsLockWithAltPress(*) {
    ; Alt+CapsLock enters the layer but does not invoke the
    ; single-tap action when released, matching the reference behavior.
    HandleCapsLockPress(false)
}

HandleCapsLockPress(runTapAction) {
    global CapsLockHeld, CapsLockUsed, CtrlZPending, KeySet
    global CapsLockTargetPath, CapsLockTargetHwnd
    if CapsLockHeld {
        DebugLog("CapsLock press ignored: layer already held")
        KeyWait("CapsLock")
        return
    }

    CapsLockHeld := true
    CapsLockUsed := false
    CtrlZPending := true
    targetWindow := GetActiveWindowInfo()
    CapsLockTargetPath := targetWindow ? targetWindow.path : ""
    CapsLockTargetHwnd := targetWindow ? targetWindow.id : 0
    ; The reference implementation only treats a release within 300ms as a
    ; tap (setCapsLock2 timer), so a long hold never fires press_caps.
    tapPending := runTapAction
    SetTimer(() => (tapPending := false), -300)
    DebugLog("CapsLockDown tapAction=" . runTapAction)

    ; The reference project keeps this handler alive until CapsLock is up.
    ; That blocks the native toggle and makes the condition-based layer
    ; available for every key pressed during the hold.
    try {
        KeyWait("CapsLock")
    } finally {
        CapsLockHeld := false
        DebugLog("CapsLockUp used=" . CapsLockUsed . " tapAction=" . tapPending)

        if tapPending && !CapsLockUsed && CapsLockTapTargetStillActive() {
            fallbackAction := KeySet.Has("press_caps") ? KeySet["press_caps"] : "keyFunc_toggleCapsLock"
            action := AppProfileResolveAction("Keys", "press_caps", fallbackAction, CapsLockTargetPath)
            if action != "@block" && action != "@native"
                RunConfiguredAction(action)
        } else if tapPending && !CapsLockUsed {
            DebugLog("CapsLock tap cancelled: active window changed")
        }
        CapsLockTargetPath := ""
        CapsLockTargetHwnd := 0
        CapsLockUsed := false
    }
}

RunLayerAction(actionKey) {
    global CapsLockUsed, KeySet
    CapsLockUsed := true
    DebugLog("Layer action=" . actionKey)
    fallbackAction := KeySet.Has(actionKey) ? KeySet[actionKey] : "keyFunc_doNothing"
    action := AppProfileResolveAction("Keys", actionKey, fallbackAction)
    if action = "@block" || action = "@native"
        return
    RunConfiguredAction(action)
}

CapsLockTapTargetStillActive() {
    global CapsLockTargetPath, CapsLockTargetHwnd
    currentWindow := GetActiveWindowInfo()
    if !currentWindow
        return false
    if CapsLockTargetHwnd
        return currentWindow.id = CapsLockTargetHwnd
    return CapsLockTargetPath != "" && StrLower(String(currentWindow.path)) = StrLower(String(CapsLockTargetPath))
}
